from rlst.core.koreapi import korea_api
from rlst.core.balance import balance
from rlst.core.stock_data_load import stock_data_loader
from rlst.strategy.find_boss import find_boss_stock

import pandas as pd

if __name__=="__main__":
    api = korea_api()
    find_boss = find_boss_stock()

    data_loader = stock_data_loader()
    #data_loader.load_index_data(".DJT", tick=True) 
    #data_loader.load_d_data('MAMA')
    #data_loader.load_m_data('MAMA', tick=True)


    codes = [
    'AACB', 'AACBU', 'AACG', 'AACI', 'AACIU', 'AADR', 'AAL', 'AALG', 'AAME',
    'AAOI', 'AAON', 'AAPB', 'AAPD', 'AAPG', 'AAPL', 'AAPU', 'AARD', 'AAUS',
    'AAVM', 'AAXJ', 'ABAT', 'ABCL', 'ABCS', 'ABEO', 'ABI', 'ABIG', 'ABL',
    'ABLLL', 'ABLV', 'ABNB', 'ABOS', 'ABP', 'ABSI', 'ABTS', 'ABUS', 'ABVC',
    'ABVE', 'ABVX', 'ACAD', 'ACB', 'ACDC', 'ACET', 'ACFN', 'ACGL', 'ACGLN',
    'ACGLO', 'ACHC', 'ACHV', 'ACIC', 'ACIU', 'ACIW', 'ACLS', 'ACLX', 'ACMR',
    'ACNB', 'ACNT', 'ACOG', 'ACON', 'ACONW', 'ACRS', 'ACRV', 'ACT', 'ACTG',
    'ACTU', 'ACWI', 'ACWX', 'ACXP', 'ADAG', 'ADAP', 'ADBE', 'ADBG', 'ADD',
    'ADEA', 'ADGM', 'ADI', 'ADIL', 'ADMA', 'ADN', 'ADNWW', 'ADP', 'ADPT',
    'ADSE', 'ADSEW', 'ADSK', 'ADTN', 'ADTX', 'ADUR', 'ADUS', 'ADV', 'ADVB',
    'ADVM', 'ADVWW', 'ADXN', 'AEBI', 'AEHL', 'AEHR', 'AEI', 'AEIS', 'AEMD',
    'AENT', 'AEP', 'AERT', 'AEVA', 'AEYE', 'AFBI', 'AFCG', 'AFJK', 'AFJKU',
    'AFOS', 'AFRI', 'AFRIW', 'AFRM', 'AFSC', 'AFYA', 'AGAE', 'AGEM', 'AGEN',
    'AGFY', 'AGGA', 'AGH', 'AGIO', 'AGIX', 'AGMH', 'AGMI', 'AGNC', 'AGNCL',
    'AGNCM', 'AGNCN', 'AGNCO', 'AGNCP', 'AGNG', 'AGRI', 'AGYS', 'AGZD',
    'AHCO', 'AHG', 'AIA', 'AIFD', 'AIFE', 'AIFEU', 'AIFF', 'AIFU', 'AIHS',
    'AIMD', 'AIOT', 'AIP', 'AIPI', 'AIPO', 'AIQ', 'AIRE', 'AIRG', 'AIRJ',
    'AIRL', 'AIRO', 'AIRR', 'AIRS', 'AIRT', 'AIRTP', 'AISP', 'AIXI', 'AKAM',
    'AKAN', 'AKBA', 'AKRO', 'AKTX', 'ALAB', 'ALAR', 'ALBT', 'ALCO', 'ALCY',
    'ALCYU', 'ALDF', 'ALDFU', 'ALDX', 'ALEC', 'ALF', 'ALFUU', 'ALGM', 'ALGN',
    'ALGS', 'ALGT', 'ALHC', 'ALIL', 'ALKS', 'ALKT', 'ALLO', 'ALLR', 'ALLT',
    'ALLW', 'ALM', 'ALMS', 'ALMU', 'ALNT', 'ALNY', 'ALOT', 'ALRM', 'ALRS',
    'ALT', 'ALTI', 'ALTO', 'ALTS', 'ALTY', 'ALVO', 'ALVOW', 'ALXO', 'ALZN',
    'AMAL', 'AMAT', 'AMBA', 'AMBR', 'AMCX', 'AMD', 'AMDD', 'AMDG', 'AMDL',
    'AMDU', 'AMED', 'AMGN', 'AMID', 'AMIX', 'AMKR', 'AMLX', 'AMOD', 'AMODW',
    'AMPG', 'AMPH', 'AMPL', 'AMRK', 'AMRN', 'AMRX', 'AMSC', 'AMSF', 'AMST',
    'AMTX', 'AMUU', 'AMWD', 'AMZD', 'AMZN', 'AMZU', 'AMZZ', 'ANAB', 'ANDE',
    'ANEB', 'ANGH', 'ANGHW', 'ANGI', 'ANGL', 'ANGO', 'ANIK', 'ANIP', 'ANIX',
    'ANL', 'ANNA', 'ANNX', 'ANPA', 'ANSC', 'ANSCU', 'ANTA', 'ANTE', 'ANTX',
    'ANY', 'AOHY', 'AOSL', 'AOTG', 'AOUT', 'APA', 'APADU', 'APDN', 'APED',
    'APEI', 'APGE', 'API', 'APLD', 'APLM', 'APLS', 'APLT', 'APM', 'APOG',
    'APP', 'APPF', 'APPN', 'APPS', 'APPX', 'APRE', 'APVO', 'APWC', 'APYX',
    'AQB', 'AQMS', 'AQST', 'AQWA', 'ARAI', 'ARAY', 'ARBB', 'ARBE', 'ARBEW',
    'ARBK', 'ARBKL', 'ARCB', 'ARCC', 'ARCT', 'ARDX', 'AREB', 'AREC', 'ARGX',
    'ARHS', 'ARKO', 'ARKOW', 'ARKR', 'ARLP', 'ARM', 'ARMG', 'AROW', 'ARQ',
    'ARQQ', 'ARQQW', 'ARQT', 'ARRY', 'ARTL', 'ARTNA', 'ARTV', 'ARTW', 'ARVN',
    'ARVR', 'ARWR', 'ASBP', 'ASET', 'ASLE', 'ASMB', 'ASMG', 'ASML', 'ASND',
    'ASNS', 'ASO', 'ASPC', 'ASPCU', 'ASPI', 'ASPS', 'ASRT', 'ASRV', 'ASST',
    'ASTC', 'ASTE', 'ASTH', 'ASTI', 'ASTL', 'ASTS', 'ASUR', 'ASYS', 'ATAI',
    'ATAT', 'ATEC', 'ATER', 'ATEX', 'ATGL', 'ATHA', 'ATHE', 'ATHR', 'ATII',
    'ATIIU', 'ATLC', 'ATLCL', 'ATLCP', 'ATLCZ', 'ATLN', 'ATLO', 'ATLX',
    'ATMC', 'ATMCU', 'ATMV', 'ATMVU', 'ATNF', 'ATNFW', 'ATNI', 'ATOM', 'ATOS',
    'ATPC', 'ATRA', 'ATRC', 'ATRO', 'ATXG', 'ATXS', 'ATYR', 'AUBN', 'AUDC',
    'AUGO', 'AUID', 'AUMI', 'AUPH', 'AUR', 'AURA', 'AUROW', 'AUTL', 'AUUD',
    'AVAH', 'AVAV', 'AVBH', 'AVBP', 'AVDL', 'AVDX', 'AVGB', 'AVGG', 'AVGO',
    'AVGU', 'AVGX', 'AVIR', 'AVL', 'AVNW', 'AVO', 'AVPT', 'AVR', 'AVS',
    'AVT', 'AVTX', 'AVUQ', 'AVXC', 'AVXL', 'AWRE', 'AXGN', 'AXIN', 'AXINU',
    'AXON', 'AXSM', 'AXTI', 'AYRO', 'AYTU', 'AZ', 'AZI', 'AZN', 'AZTA',
    'BABX', 'BACC', 'BACCU', 'BACQ', 'BACQU', 'BAER', 'BAERW', 'BAFE',
    'BAFN', 'BAIG', 'BAND', 'BANF', 'BANFP', 'BANL', 'BANR', 'BANX', 'BAOS',
    'BASE', 'BASG', 'BASV', 'BATRA', 'BATRK', 'BAYA', 'BAYAU', 'BBCP', 'BBGI',
    'BBH', 'BBIO', 'BBLG', 'BBLGW', 'BBNX', 'BBOT', 'BBSI', 'BCAB', 'BCAL',
    'BCAR', 'BCARU', 'BCAX', 'BCBP', 'BCDA', 'BCG', 'BCLO', 'BCML', 'BCPC',
    'BCRX', 'BCTX', 'BCYC', 'BDGS', 'BDMD', 'BDRX', 'BDSX', 'BDTX', 'BEAG',
    'BEAGU', 'BEAM', 'BEAT', 'BEATW', 'BEEM', 'BEEP', 'BEEX', 'BEEZ', 'BELFA',
    'BELFB', 'BELT', 'BENF', 'BENFW', 'BETR', 'BFC', 'BFIN', 'BFRG', 'BFRGW',
    'BFRI', 'BFST', 'BGC', 'BGFV', 'BGL', 'BGLC', 'BGM', 'BGRN', 'BGRO',
    'BHAT', 'BHF', 'BHFAL', 'BHFAM', 'BHFAN', 'BHFAO', 'BHFAP', 'BHRB',
    'BHST', 'BIAF', 'BIB', 'BIDU', 'BIGC', 'BIIB', 'BILI', 'BINI', 'BIOA',
    'BIOX', 'BIRD', 'BIS', 'BITF', 'BITS', 'BIVI', 'BIYA', 'BJDX', 'BJK',
    'BJRI', 'BKCH', 'BKHA', 'BKHAU', 'BKIV', 'BKNG', 'BKR', 'BKWO', 'BKYI',
    'BL', 'BLBD', 'BLBX', 'BLCN', 'BLCR', 'BLDE', 'BLDP', 'BLFS', 'BLFY',
    'BLIN', 'BLIV', 'BLKB', 'BLMN', 'BLMZ', 'BLNE', 'BLNK', 'BLRX', 'BLTE',
    'BLUW', 'BLUWU', 'BLZE', 'BMAX', 'BMBL', 'BMDL', 'BMEA', 'BMGL', 'BMHL',
    'BMR', 'BMRA', 'BMRC', 'BMRN', 'BNAI', 'BNC', 'BND', 'BNDW', 'BNDX',
    'BNGO', 'BNR', 'BNRG', 'BNTX', 'BNZI', 'BOED', 'BOEG', 'BOEU',
    'BOF', 'BOKF', 'BOLD', 'BOLT', 'BON', 'BOOM', 'BOSC', 'BOTJ', 'BOTT',
    'BOTZ', 'BOWN', 'BOWNU', 'BOXL', 'BPMC', 'BPOP', 'BPOPM', 'BPRN', 'BPYPM',
    'BPYPN', 'BPYPO', 'BPYPP', 'BRAG', 'BREA', 'BRFH', 'BRHY', 'BRID', 'BRKD',
    'BRKL', 'BRKR', 'BRKU', 'BRLS', 'BRLT', 'BRNS', 'BRNY', 'BRR', 'BRRR',
    'BRRWU', 'BRTR', 'BRTX', 'BRY', 'BRZE', 'BSAA', 'BSAAU', 'BSBK', 'BSCP',
    'BSCQ', 'BSCR', 'BSCS', 'BSCT', 'BSCU', 'BSCV', 'BSCW', 'BSCX', 'BSCY',
    'BSCZ', 'BSET', 'BSGM', 'BSJP', 'BSJQ', 'BSJR', 'BSJS', 'BSJT', 'BSJU',
    'BSJV', 'BSJW', 'BSJX', 'BSLK', 'BSMP', 'BSMQ', 'BSMR', 'BSMS', 'BSMT',
    'BSMU', 'BSMV', 'BSMW', 'BSMY', 'BSRR', 'BSSX', 'BSVN', 'BSVO', 'BSY',
    'BTAI', 'BTBD', 'BTBT', 'BTCS', 'BTCT', 'BTDR', 'BTF', 'BTFX', 'BTGD',
    'BTM', 'BTMD', 'BTOC', 'BTOG', 'BTSG', 'BTSGU', 'BUFC', 'BUFI', 'BUFM',
    'BUG', 'BULD', 'BULG', 'BULL', 'BUSE', 'BUSEP', 'BUUU', 'BVFL', 'BVS',
    'BWAY', 'BWB', 'BWBBP', 'BWEN', 'BWFG', 'BWIN', 'BWMN', 'BYFC', 'BYND',
    'BYRN', 'BYSI', 'BZ', 'BZAI', 'BZFD', 'BZFDW', 'BZUN', 'CA', 'CAAS',
    'CABA', 'CAC', 'CACC', 'CADL', 'CAEP', 'CAFG', 'CAI', 'CAKE', 'CALC',
    'CALI', 'CALM', 'CAMP', 'CAMT', 'CAN', 'CANC', 'CANQ', 'CAPN', 'CAPNU',
    'CAPR', 'CAPS', 'CAPT', 'CAR', 'CARE', 'CARG', 'CARL', 'CARM', 'CART',
    'CARV', 'CARY', 'CARZ', 'CASH', 'CASI', 'CASK', 'CASS', 'CASY', 'CATH',
    'CATY', 'CBAT', 'CBFV', 'CBIO', 'CBLL', 'CBNK', 'CBRL', 'CBSH', 'CBUS',
    'CCAP', 'CCB', 'CCBG', 'CCCC', 'CCCM', 'CCCMU', 'CCCS', 'CCCX', 'CCCXU',
    'CCD', 'CCEC', 'CCEP', 'CCFE', 'CCG', 'CCII', 'CCIIU', 'CCIR', 'CCIRU',
    'CCIX', 'CCIXU', 'CCLD', 'CCLDO', 'CCNE', 'CCNEP', 'CCNR', 'CCOI',
    'CCRN', 'CCSB', 'CCSI', 'CCSO', 'CCTG', 'CDC', 'CDIO', 'CDIOW', 'CDL',
    'CDLX', 'CDNA', 'CDNS', 'CDRO', 'CDROW', 'CDT', 'CDTG', 'CDTX', 'CDW',
    'CDXS', 'CDZI', 'CDZIP', 'CECO', 'CEFA', 'CEG', 'CELC', 'CELH', 'CELU',
    'CELZ', 'CENN', 'CENT', 'CENTA', 'CENX', 'CEP', 'CEPF', 'CEPI', 'CEPO',
    'CEPT', 'CERO', 'CERS', 'CERT', 'CETX', 'CETY', 'CEVA', 'CFA', 'CFBK',
    'CFFI', 'CFFN', 'CFLT', 'CFO', 'CFSB', 'CG', 'CGABL', 'CGBD', 'CGBDL',
    'CGC', 'CGCT', 'CGCTU', 'CGEM', 'CGEN', 'CGNT', 'CGNX', 'CGO', 'CGON',
    'CGTL', 'CGTX', 'CHA', 'CHAC', 'CHACU', 'CHAR', 'CHARU', 'CHCI', 'CHCO',
    'CHDN', 'CHEF', 'CHEK', 'CHGX', 'CHI', 'CHKP', 'CHMG', 'CHNR', 'CHPG',
    'CHPGU', 'CHPS', 'CHR', 'CHRD', 'CHRS', 'CHRW', 'CHSCL', 'CHSCM',
    'CHSCN', 'CHSCO', 'CHSCP', 'CHSN', 'CHTR', 'CHW', 'CHY', 'CHYM', 'CIBR',
    'CIFR', 'CIGI', 'CIGL', 'CIIT', 'CIL', 'CINF', 'CING', 'CISO', 'CISS',
    'CIVB', 'CJET', 'CJMB', 'CLAR', 'CLBK', 'CLBT', 'CLDX', 'CLFD', 'CLGN',
    'CLIK', 'CLIR', 'CLLS', 'CLMB', 'CLMT', 'CLNE', 'CLNN', 'CLNNW', 'CLOA',
    'CLOD', 'CLOU', 'CLOV', 'CLPS', 'CLPT', 'CLRB', 'CLRO', 'CLSD', 'CLSK',
    'CLSM', 'CLST', 'CLWT', 'CLYM', 'CMBM', 'CMCO', 'CMCSA', 'CMCT', 'CME',
    'CMMB', 'CMND', 'CMPO', 'CMPOW', 'CMPR', 'CMPS', 'CMPX', 'CMRC', 'CMTL',
    'CNCK', 'CNDT', 'CNET', 'CNEY', 'CNFR', 'CNFRZ', 'CNOB', 'CNOBP', 'CNSP',
    'CNTA', 'CNTB', 'CNTX', 'CNTY', 'CNVS', 'CNXC', 'CNXN', 'COCH', 'COCO',
    'COCP', 'CODA', 'CODX', 'COEP', 'COEPW', 'COFS', 'COGT', 'COHU', 'COIG',
    'COIN', 'COKE', 'COLA', 'COLAU', 'COLB', 'COLL', 'COLM', 'COMM', 'COMT',
    'CONI', 'CONL', 'COO', 'COOP', 'COOT', 'COPJ', 'COPP', 'CORO', 'CORT',
    'CORZ', 'CORZZ', 'COSM', 'COST', 'COWG', 'COWS', 'COYA', 'COYY', 'CPAG',
    'CPB', 'CPBI', 'CPHC', 'CPHY', 'CPIX', 'CPLS', 'CPOP', 'CPRT', 'CPRX',
    'CPSH', 'CPSS', 'CPZ', 'CRAI', 'CRAQ', 'CRAQU', 'CRBP', 'CRBU', 'CRCG',
    'CRCT', 'CRDF', 'CRDL', 'CRDO', 'CRE', 'CREG', 'CRESY', 'CREV', 'CREX',
    'CRGO', 'CRGOW', 'CRGX', 'CRIS', 'CRMD', 'CRMG', 'CRML', 'CRMT', 'CRNC',
    'CRNT', 'CRNX', 'CRON', 'CROX', 'CRSP', 'CRSR', 'CRTO', 'CRUS', 'CRVL',
    'CRVO', 'CRVS', 'CRWD', 'CRWG', 'CRWL', 'CRWS', 'CRWV', 'CSAI', 'CSB',
    'CSBR', 'CSCI', 'CSCL', 'CSCO', 'CSCS', 'CSGP', 'CSGS', 'CSIQ', 'CSPI',
    'CSQ', 'CSTE', 'CSTL', 'CSWC', 'CSWCZ', 'CSX', 'CTAS', 'CTBI', 'CTEC',
    'CTKB', 'CTLP', 'CTMX', 'CTNM', 'CTNT', 'CTOR', 'CTRM', 'CTRN', 'CTSH',
    'CTSO', 'CTW', 'CTXR', 'CUB', 'CUBWU', 'CUE', 'CUPR', 'CURI', 'CURIW',
    'CURR', 'CV', 'CVAC', 'CVBF', 'CVCO', 'CVGI', 'CVGW', 'CVKD', 'CVLT',
    'CVNX', 'CVRX', 'CVV', 'CWBC', 'CWCO', 'CWD', 'CWST', 'CXAI', 'CXAIW',
    'CXDO', 'CXSE', 'CYBR', 'CYCC', 'CYCCP', 'CYCN', 'CYCU', 'CYN', 'CYRX',
    'CYTK', 'CZAR', 'CZFS', 'CZNC', 'CZR', 'CZWI', 'DAAQ', 'DAAQU', 'DADS',
    'DAIC', 'DAIO', 'DAK', 'DAKT', 'DALI', 'DALN', 'DAPP', 'DARE', 'DASH',
    'DATS', 'DAVE', 'DAVEW', 'DAWN', 'DAX', 'DBGI', 'DBVT', 'DBX', 'DCBO',
    'DCGO', 'DCOM', 'DCOMG', 'DCOMP', 'DCTH', 'DDI', 'DDIV', 'DDOG', 'DECO',
    'DEFT', 'DEMZ', 'DENN', 'DERM', 'DEVS', 'DFDV', 'DFGP', 'DFGX', 'DFLI',
    'DFLIW', 'DFSC', 'DGCB', 'DGICA', 'DGICB', 'DGII', 'DGLO', 'DGLY',
    'DGNX', 'DGRE', 'DGRS', 'DGRW', 'DGXX', 'DH', 'DHAI', 'DHC', 'DHCNI',
    'DHCNL', 'DHIL', 'DIBS', 'DIOD', 'DIVD', 'DJCO', 'DJT', 'DKI', 'DKNG',
    'DKNX', 'DLHC', 'DLLL', 'DLO', 'DLPN', 'DLTH', 'DLTR', 'DLXY', 'DMAA',
    'DMAAU', 'DMAC', 'DMAT', 'DMLP', 'DMRC', 'DMXF', 'DNLI', 'DNTH', 'DNUT',
    'DOCU', 'DOGZ', 'DOMH', 'DOMO', 'DOOO', 'DORM', 'DOX', 'DOYU', 'DPRO',
    'DPZ', 'DRCT', 'DRDB', 'DRDBU', 'DRIO', 'DRIV', 'DRMA', 'DRRX', 'DRS',
    'DRTS', 'DRTSW', 'DRUG', 'DRVN', 'DSGN', 'DSGR', 'DSGX', 'DSP', 'DSWL',
    'DSY', 'DTCK', 'DTCR', 'DTI', 'DTIL', 'DTSQ', 'DTSQU', 'DTSS', 'DTST',
    'DUKH', 'DUKX', 'DUO', 'DUOL', 'DUOT', 'DVAL', 'DVAX', 'DVIN', 'DVLT',
    'DVLU', 'DVOL', 'DVQQ', 'DVRE', 'DVSP', 'DVUT', 'DVXB', 'DVXC', 'DVXE',
    'DVXF', 'DVXK', 'DVXP', 'DVXV', 'DVXY', 'DVY', 'DWAS', 'DWAW', 'DWSH',
    'DWSN', 'DWTX', 'DWUS', 'DXCM', 'DXLG', 'DXPE', 'DXR', 'DXST', 'DYAI',
    'DYCQ', 'DYCQU', 'DYFI', 'DYN', 'DYNX', 'DYNXU', 'DYTA', 'EA', 'EBAY',
    'EBC', 'EBI', 'EBIZ', 'EBMT', 'EBON', 'ECBK', 'ECDA', 'ECOR', 'ECOW',
    'ECPG', 'ECX', 'ECXWW', 'EDAP', 'EDBL', 'EDHL', 'EDIT', 'EDRY', 'EDSA',
    'EDTK', 'EDUC', 'EEFT', 'EEIQ', 'EEMA', 'EFAS', 'EFOI', 'EFRA', 'EFSC',
    'EFSCP', 'EFSI', 'EFTY', 'EGAN', 'EGBN', 'EGGQ', 'EGHA', 'EGHAU', 'EGHT',
    'EH', 'EHGO', 'EHLD', 'EHLS', 'EHTH', 'EJH', 'EKG', 'EKSO', 'ELAB',
    'ELBM', 'ELDN', 'ELEV', 'ELFY', 'ELIL', 'ELIS', 'ELPW', 'ELSE', 'ELTK',
    'ELTX', 'ELUT', 'ELVA', 'ELVN', 'ELWS', 'EM', 'EMB', 'EMBC', 'EMCB',
    'EMCG', 'EMCGU', 'EMEQ', 'EMIF', 'EML', 'EMPD', 'EMPG', 'EMXC', 'EMXF',
    'ENDW', 'ENGN', 'ENGS', 'ENLT', 'ENLV', 'ENPH', 'ENSC', 'ENSG', 'ENTA',
    'ENTG', 'ENTO', 'ENTX', 'ENVB', 'ENVX', 'ENZL', 'EOLS', 'EOSE', 'EOSEW',
    'EPIX', 'EPOW', 'EPRX', 'EPSM', 'EPSN', 'EPWK', 'EQ', 'EQIX', 'EQRR',
    'ERAS', 'ERET', 'ERIC', 'ERIE', 'ERII', 'ERNA', 'ERNZ', 'ESCA', 'ESEA',
    'ESGD', 'ESGE', 'ESGL', 'ESGU', 'ESHA', 'ESLA', 'ESLT', 'ESMV', 'ESN',
    'ESOA', 'ESPO', 'ESPR', 'ESQ', 'ESTA', 'ETEC', 'ETHA', 'ETHZ',
    'ETHZW', 'ETNB', 'ETON', 'ETOR', 'ETS', 'ETSY', 'EU', 'EUDA', 'EUDAW',
    'EUFN', 'EURK', 'EURKU', 'EVAX', 'EVCM', 'EVER', 'EVGN', 'EVGO', 'EVGOW',
    'EVLV', 'EVLVW', 'EVMT', 'EVO', 'EVOK', 'EVRG', 'EVSD', 'EVTV', 'EVYM',
    'EWBC', 'EWCZ', 'EWJV', 'EWTX', 'EWZS', 'EXAS', 'EXC', 'EXE', 'EXEL',
    'EXFY', 'EXLS', 'EXOZ', 'EXPE', 'EXPI', 'EXPO', 'EXTR', 'EXUS', 'EYE',
    'EYEG', 'EYPT', 'EZGO', 'EZPW', 'FA', 'FAAR', 'FAAS', 'FAB', 'FACT',
    'FACTU', 'FAD', 'FALN', 'FAMI', 'FANG', 'FARM', 'FARO', 'FAST', 'FAT',
    'FATBB', 'FATBP', 'FATE', 'FATN', 'FBGL', 'FBIO', 'FBIOP', 'FBIZ', 'FBL',
    'FBLA', 'FBLG', 'FBNC', 'FBOT', 'FBRX', 'FBYD', 'FCA', 'FCAL', 'FCAP',
    'FCBC', 'FCCO', 'FCEF', 'FCEL', 'FCFS', 'FCNCA', 'FCNCO', 'FCNCP',
    'FCTE', 'FCUV', 'FCVT', 'FDBC', 'FDCF', 'FDFF', 'FDIF', 'FDIG', 'FDIV',
    'FDMT', 'FDNI', 'FDSB', 'FDT', 'FDTS', 'FDTX', 'FDUS', 'FEAM', 'FEAT',
    'FEBO', 'FEIM', 'FELE', 'FEM', 'FEMB', 'FEMS', 'FEMY', 'FENC', 'FEP',
    'FEPI', 'FER', 'FERA', 'FERAU', 'FEUZ', 'FEX', 'FFAI', 'FFBC', 'FFFZ',
    'FFIC', 'FFIN', 'FFIV', 'FFUT', 'FGBI', 'FGBIP', 'FGEN', 'FGF', 'FGFPP',
    'FGI', 'FGL', 'FGM', 'FGMC', 'FGMCU', 'FGNX', 'FGNXP', 'FGSI', 'FGXCU',
    'FHB', 'FHTX', 'FIBK', 'FICS', 'FID', 'FIEE', 'FIGX', 'FIGXU', 'FINE',
    'FINW', 'FINX', 'FIP', 'FISI', 'FITB', 'FITBI', 'FITBO', 'FITBP', 'FIVE',
    'FIVN', 'FIVY', 'FIXD', 'FIZZ', 'FJP', 'FKU', 'FKWL', 'FLD',
    'FLEX', 'FLGC', 'FLGT', 'FLL', 'FLN', 'FLNC', 'FLNT', 'FLUX', 'FLWS',
    'FLX', 'FLXS', 'FLY', 'FLYE', 'FLYW', 'FMAO', 'FMB', 'FMBH', 'FMED',
    'FMET', 'FMFC', 'FMHI', 'FMNB', 'FMST', 'FMTM', 'FMUB', 'FMUN', 'FNGR',
    'FNK', 'FNKO', 'FNLC', 'FNWB', 'FNWD', 'FNX', 'FNY', 'FOLD', 'FONR',
    'FORA', 'FORD', 'FORL', 'FORLU', 'FORM', 'FORR', 'FORTY', 'FOSL',
    'FOSLL', 'FOX', 'FOXA', 'FOXF', 'FOXX', 'FPA', 'FPAY', 'FPXE', 'FPXI',
    'FRAF', 'FRBA', 'FRD', 'FRDD', 'FRDU', 'FRGT', 'FRHC', 'FRME', 'FRMEP',
    'FROG', 'FRPH', 'FRPT', 'FRSH', 'FRST', 'FRSX', 'FSBC', 'FSBW', 'FSCS',
    'FSEA', 'FSFG', 'FSGS', 'FSHP', 'FSHPU', 'FSLR', 'FSTR', 'FSUN', 'FSV',
    'FSZ', 'FTA', 'FTAG', 'FTAI', 'FTAIM', 'FTAIN', 'FTC', 'FTCI', 'FTCS',
    'FTDR', 'FTDS', 'FTEK', 'FTEL', 'FTFT', 'FTGC', 'FTGS', 'FTHI', 'FTHM',
    'FTLF', 'FTNT', 'FTQI', 'FTRE', 'FTRI', 'FTRK', 'FTSL', 'FTSM', 'FTXG',
    'FTXH', 'FTXL', 'FTXN', 'FTXO', 'FTXR', 'FUFU', 'FULC', 'FULT', 'FULTP',
    'FUNC', 'FUND', 'FUSB', 'FUTU', 'FV', 'FVC', 'FVCB', 'FVN', 'FVNNU',
    'FWONA', 'FWONK', 'FWRD', 'FWRG', 'FXNC', 'FYBR', 'FYC', 'FYT', 'FYX',
    'GABC', 'GAIA', 'GAIN', 'GAINI', 'GAINL', 'GAINN', 'GAINZ', 'GALT',
    'GAMB', 'GAME', 'GANX', 'GASS', 'GAUZ', 'GBDC', 'GBFH', 'GBIO', 'GBUG',
    'GCBC', 'GCL', 'GCMG', 'GCMGW', 'GCT', 'GCTK', 'GDC', 'GDEN', 'GDEV',
    'GDHG', 'GDRX', 'GDS', 'GDTC', 'GDYN', 'GECC', 'GECCH', 'GECCI', 'GECCO',
    'GECCZ', 'GEG', 'GEGGL', 'GEHC', 'GELS', 'GEME', 'GEN', 'GENK', 'GEOS',
    'GERN', 'GEVO', 'GFAI', 'GFGF', 'GFLW', 'GFS', 'GGAL', 'GGLL', 'GGLS',
    'GGR', 'GH', 'GHRS', 'GIBO', 'GIFI', 'GIFT', 'GIG', 'GIGGU', 'GIGM',
    'GIII', 'GILD', 'GILT', 'GIND', 'GINX', 'GIPR', 'GITS', 'GLAD', 'GLADZ',
    'GLBE', 'GLBS', 'GLBZ', 'GLCR', 'GLDD', 'GLDI', 'GLDY', 'GLE', 'GLGG',
    'GLIBA', 'GLIBK', 'GLMD', 'GLNG', 'GLOW', 'GLPG', 'GLPI', 'GLRE', 'GLSI',
    'GLTO', 'GLUE', 'GLXG', 'GLXY', 'GMAB', 'GMGI', 'GMHS', 'GMM', 'GNFT',
    'GNLN', 'GNLX', 'GNMA', 'GNOM', 'GNPX', 'GNSS', 'GNTA', 'GNTX', 'GO',
    'GOCO', 'GOGL', 'GOGO', 'GOOD', 'GOODN', 'GOODO', 'GOOG', 'GOOGL',
    'GORV', 'GOSS', 'GOVI', 'GOVX', 'GP', 'GPAT', 'GPATU', 'GPCR', 'GPIQ',
    'GPIX', 'GPRE', 'GPRF', 'GPRO', 'GQQQ', 'GRAB', 'GRABW', 'GRAL', 'GRAN',
    'GRCE', 'GREE', 'GREEL', 'GRFS', 'GRI', 'GRID', 'GRIN', 'GRNQ', 'GROW',
    'GRPN', 'GRRR', 'GRRRW', 'GRVY', 'GRW', 'GRWG', 'GRYP', 'GSAT', 'GSBC',
    'GSHD', 'GSHR', 'GSHRU', 'GSIB', 'GSIT', 'GSIW', 'GSM', 'GSRT', 'GSRTU',
    'GSUN', 'GT', 'GTBP', 'GTEC', 'GTEN', 'GTENU', 'GTERA', 'GTERU', 'GTI',
    'GTIM', 'GTLB', 'GTM', 'GTR', 'GTX', 'GURE', 'GUTS', 'GV', 'GVH', 'GWAV',
    'GWRS', 'GXAI', 'GXDW', 'GYRE', 'GYRO', 'HAFC', 'HAIN', 'HALO', 'HAO',
    'HAS', 'HBAN', 'HBANL', 'HBANM', 'HBANP', 'HBCP', 'HBDC', 'HBIO', 'HBNB',
    'HBNC', 'HBT', 'HCAI', 'HCAT', 'HCHL', 'HCKT', 'HCM', 'HCMAU', 'HCOW',
    'HCSG', 'HCTI', 'HCWB', 'HDL', 'HDSN', 'HEAL', 'HECO', 'HEJD', 'HELE',
    'HEPS', 'HEQQ', 'HERD', 'HERO', 'HERZ', 'HFBL', 'HFFG', 'HFSP', 'HFWA',
    'HGBL', 'HHS', 'HIDE', 'HIFS', 'HIHO', 'HIMX', 'HIMY', 'HIMZ', 'HIND',
    'HISF', 'HIT', 'HITI', 'HIVE', 'HKIT', 'HKPD', 'HLAL', 'HLIT', 'HLMN',
    'HLNE', 'HLP', 'HLVX', 'HLXB', 'HMR', 'HMST', 'HNDL', 'HNNA', 'HNNAZ',
    'HNRG', 'HNST', 'HNVR', 'HOFT', 'HOLO', 'HOLOW', 'HOLX', 'HON', 'HOND',
    'HONDU', 'HONE', 'HOOD', 'HOOG', 'HOOI', 'HOOK', 'HOOX', 'HOPE', 'HOTH',
    'HOUR', 'HOVNP', 'HOVR', 'HOWL', 'HPAI', 'HPK', 'HQGO', 'HQI', 'HQY',
    'HRMY', 'HROW', 'HROWL', 'HROWM', 'HRTS', 'HRTX', 'HRZN', 'HSAI', 'HSCS',
    'HSDT', 'HSIC', 'HSII', 'HSON', 'HSONP', 'HSPO', 'HSPOU', 'HSPT', 'HSPTU',
    'HST', 'HSTM', 'HTBK', 'HTCO', 'HTCR', 'HTFL', 'HTHT', 'HTLD', 'HTLM',
    'HTO', 'HTOO', 'HTZ', 'HTZWW', 'HUBC', 'HUBCW', 'HUBG', 'HUDI', 'HUHU',
    'HUIZ', 'HUMA', 'HURA', 'HURC', 'HURN', 'HUT', 'HVII', 'HVIIU', 'HVMCU',
    'HWAY', 'HWBK', 'HWC', 'HWCPZ', 'HWH', 'HWKN', 'HWSM', 'HXHX', 'HYBI',
    'HYDR', 'HYFM', 'HYLS', 'HYMC', 'HYMCL', 'HYPD', 'HYPR', 'HYXF', 'HYZD',
    'IAC', 'IART', 'IAS', 'IBAC', 'IBAT', 'IBB', 'IBBQ', 'IBCP', 'IBEX',
    'IBG', 'IBGA', 'IBGB', 'IBGK', 'IBGL', 'IBIO', 'IBIT', 'IBKR', 'IBOC',
    'IBOT', 'IBRX', 'IBTF', 'IBTG', 'IBTH', 'IBTI', 'IBTJ', 'IBTK', 'IBTL',
    'IBTM', 'IBTO', 'IBTP', 'IBTQ', 'ICCC', 'ICCM', 'ICFI', 'ICG', 'ICHR',
    'ICLN', 'ICLR', 'ICMB', 'ICON', 'ICOP', 'ICU', 'ICUCW', 'ICUI', 'IDAI',
    'IDCC', 'IDEF', 'IDN', 'IDXX', 'IDYA', 'IEF', 'IEI', 'IEP', 'IESC',
    'IEUS', 'IFBD', 'IFGL', 'IFLO', 'IFRX', 'IFV', 'IGF', 'IGIB', 'IGIC',
    'IGMS', 'IGOV', 'IGSB', 'IHRT', 'IHYF', 'III', 'IIIV', 'IINN', 'IJT',
    'IKNA', 'IKT', 'ILAG', 'ILIT', 'ILLR', 'ILMN', 'ILPT', 'IMA', 'IMAB',
    'IMCC', 'IMCR', 'IMCV', 'IMDX', 'IMG', 'IMKTA', 'IMMP', 'IMMR', 'IMMX',
    'IMNM', 'IMNN', 'IMOM', 'IMOS', 'IMPP', 'IMPPP', 'IMRN', 'IMRX', 'IMTE',
    'IMTX', 'IMUX', 'IMVT', 'IMXI', 'INAB', 'INAC', 'INACU', 'INBK', 'INBKZ',
    'INBS', 'INBX', 'INCR', 'INCY', 'INDB', 'INDH', 'INDI', 'INDP', 'INDV',
    'INDY', 'INEO', 'INFR', 'INGN', 'INHD', 'INKT', 'INLF', 'INM', 'INMB',
    'INMD', 'INNV', 'INO', 'INOD', 'INRO', 'INSE', 'INSG', 'INSM', 'INTA',
    'INTC', 'INTG', 'INTJ', 'INTR', 'INTS', 'INTU', 'INTW', 'INTZ', 'INV',
    'INVA', 'INVE', 'INVZ', 'IOBT', 'IONL', 'IONR', 'IONS', 'IONX', 'IONZ',
    'IOSP', 'IOTR', 'IOVA', 'IPA', 'IPAR', 'IPCX', 'IPCXU', 'IPDN', 'IPGP',
    'IPHA', 'IPKW', 'IPM', 'IPOD', 'IPODU', 'IPSC', 'IPW', 'IPWR', 'IPX',
    'IQ', 'IQQQ', 'IQST', 'IRBT', 'IRD', 'IRDM', 'IREN', 'IRIX', 'IRMD',
    'IROH', 'IROHU', 'IRON', 'IROQ', 'IRTC', 'IRWD', 'ISBA', 'ISHG', 'ISHP',
    'ISPC', 'ISPO', 'ISPOW', 'ISPR', 'ISRG', 'ISRL', 'ISRLU', 'ISSC', 'ISTB',
    'ISTR', 'ITIC', 'ITOS', 'ITRI', 'ITRM', 'ITRN', 'IUS', 'IUSB', 'IUSG',
    'IUSV', 'IVA', 'IVAL', 'IVDA', 'IVEG', 'IVF', 'IVP', 'IVVD', 'IWTR',
    'IXHL', 'IXUS', 'IZEA', 'IZM', 'JACK', 'JAGX', 'JAKK', 'JAMF', 'JANX',
    'JAPN', 'JAZZ', 'JBDI', 'JBHT', 'JBIO', 'JBLU', 'JBSS', 'JCAP', 'JCSE',
    'JCTC', 'JD', 'JDOC', 'JDZG', 'JEM', 'JEPQ', 'JFB', 'JFBR', 'JFIN',
    'JFU', 'JG', 'JGLO', 'JHAI', 'JIVE', 'JJSF', 'JKHY', 'JL', 'JLHL',
    'JMID', 'JMSB', 'JOUT', 'JOYY', 'JPEF', 'JPX', 'JPY', 'JRSH', 'JRVR',
    'JSM', 'JSMD', 'JSML', 'JSPR', 'JSPRW', 'JTAI', 'JTEK', 'JUNS', 'JVA',
    'JWEL', 'JXG', 'JYD', 'JYNT', 'JZ', 'JZXN', 'KALA', 'KALU', 'KALV',
    'KARO', 'KAVL', 'KBAB', 'KBSX', 'KBWB', 'KBWD', 'KBWP', 'KBWR', 'KBWY',
    'KC', 'KCHV', 'KCHVU', 'KDP', 'KE', 'KEAT', 'KELYA', 'KELYB', 'KEQU',
    'KFFB', 'KFII', 'KFIIU', 'KG', 'KGEI', 'KHC', 'KIDS', 'KIDZ', 'KINS',
    'KIRK', 'KITT', 'KITTW', 'KLAC', 'KLIC', 'KLRS', 'KLTO', 'KLTR', 'KLXE',
    'KMB', 'KMDA', 'KMLI', 'KMRK', 'KNDI', 'KNGZ', 'KNSA', 'KOD',
    'KOID', 'KOPN', 'KOSS', 'KPDD', 'KPLT', 'KPRX', 'KPTI', 'KQQQ', 'KRKR',
    'KRMA', 'KRMD', 'KRNT', 'KRNY', 'KROP', 'KROS', 'KRRO', 'KRT', 'KRUS',
    'KRYS', 'KSCP', 'KSPI', 'KTCC', 'KTOS', 'KTTA', 'KURA', 'KVAC', 'KVACU',
    'KVHI', 'KWM', 'KXIN', 'KYIV', 'KYMR', 'KYTX', 'KZIA', 'KZR', 'LAB',
    'LAES', 'LAKE', 'LAMR', 'LAND', 'LANDM', 'LANDO', 'LANDP', 'LARK',
    'LASE', 'LASR', 'LAUR', 'LAWR', 'LAYS', 'LAZR', 'LBGJ', 'LBRDA',
    'LBRDK', 'LBRDP', 'LBTYA', 'LBTYB', 'LBTYK', 'LCCC', 'LCCCU', 'LCDL',
    'LCDS', 'LCFY', 'LCFYW', 'LCID', 'LCNB', 'LCUT', 'LDEM', 'LDRX', 'LDSF',
    'LDWY', 'LE', 'LECO', 'LEDS', 'LEE', 'LEGH', 'LEGN', 'LEGR', 'LENZ',
    'LESL', 'LEXI', 'LEXX', 'LFCR', 'LFMD', 'LFMDP', 'LFSC', 'LFST', 'LFUS',
    'LFVN', 'LFWD', 'LGCB', 'LGCF', 'LGCL', 'LGHL', 'LGIH', 'LGND', 'LGO',
    'LGRO', 'LGVN', 'LHAI', 'LHSW', 'LI', 'LICN', 'LIDR', 'LIEN', 'LIF',
    'LILA', 'LILAK', 'LIMN', 'LIN', 'LINC', 'LIND', 'LINE', 'LINK', 'LIQT',
    'LITE', 'LITM', 'LITP', 'LIVE', 'LIVN', 'LIVR', 'LIXT', 'LIXTW', 'LKFN',
    'LKQ', 'LLYVA', 'LLYVK', 'LMAT', 'LMB', 'LMBS', 'LMFA', 'LMNR', 'LMTL',
    'LMTS', 'LNKB', 'LNKS', 'LNSR', 'LNT', 'LNTH', 'LNW', 'LNZA', 'LNZAW',
    'LOAN', 'LOBO', 'LOCO', 'LOGI', 'LOGO', 'LOKV', 'LOKVU', 'LOOP', 'LOPE',
    'LOT', 'LOVE', 'LPAA', 'LPAAU', 'LPBB', 'LPBBU', 'LPCN', 'LPLA', 'LPRO',
    'LPSN', 'LPTH', 'LPTX', 'LQDA', 'LQDT', 'LRCX', 'LRE', 'LRGE', 'LRHC',
    'LRMR', 'LRND', 'LSAK', 'LSB', 'LSBK', 'LSBPW', 'LSCC', 'LSE', 'LSH',
    'LSTA', 'LSTR', 'LTBR', 'LTRN', 'LTRX', 'LTRYW', 'LUCD', 'LUCY', 'LULU',
    'LUNG', 'LUNR', 'LVHD', 'LVLU', 'LVO', 'LVRO', 'LVTX', 'LWAC', 'LWACU',
    'LWAY', 'LWLG', 'LX', 'LXEH', 'LXEO', 'LXRX', 'LYEL', 'LYFT', 'LYRA',
    'LYTS', 'LZ', 'LZMH', 'MAAS', 'MACI', 'MACIU', 'MAGH', 'MAMA', 'MAMK',
    'MAMO', 'MANH', 'MAPS', 'MAR', 'MARA', 'MARPS', 'MASI', 'MASK', 'MASS',
    'MAT', 'MATH', 'MATW', 'MAXI', 'MAXN', 'MAYA', 'MAYAU', 'MAYS', 'MAZE',
    'MB', 'MBAV', 'MBAVU', 'MBB', 'MBBC', 'MBCN', 'MBIN', 'MBINL', 'MBINM',
    'MBINN', 'MBIO', 'MBLY', 'MBNKO', 'MBOT', 'MBRX', 'MBS', 'MBUU', 'MBWM',
    'MBX', 'MCBS', 'MCDS', 'MCFT', 'MCHI', 'MCHP', 'MCHPP', 'MCHS', 'MCHX',
    'MCRB', 'MCRI', 'MCSE', 'MCTR', 'MCVT', 'MCW', 'MDAI', 'MDB', 'MDBH',
    'MDCX', 'MDGL', 'MDIA', 'MDIV', 'MDLZ', 'MDRR', 'MDWD', 'MDXG', 'MDXH',
    'MEDP', 'MEDX', 'MEGL', 'MEIP', 'MELI', 'MEMS', 'MENS', 'MEOH', 'MERC',
    'MESA', 'MESO', 'META', 'METC', 'METCB', 'METCI', 'METCL', 'METCZ',
    'METD', 'METU', 'MFH', 'MFI', 'MFIC', 'MFIN', 'MFLX', 'MGEE', 'MGIC',
    'MGIH', 'MGNI', 'MGNX', 'MGPI', 'MGRC', 'MGRM', 'MGRT', 'MGRX', 'MGTX',
    'MGX', 'MGYR', 'MHUA', 'MIDD', 'MIGI', 'MILN', 'MIMI', 'MIND', 'MIRA',
    'MIRM', 'MIST', 'MITK', 'MJID', 'MKAM', 'MKDW', 'MKLYU', 'MKSI', 'MKTW',
    'MKTX', 'MKZR', 'MLAB', 'MLAC', 'MLACU', 'MLCO', 'MLEC', 'MLECW', 'MLGO',
    'MLKN', 'MLTX', 'MLYS', 'MMLP', 'MMSI', 'MMYT', 'MNDO', 'MNDR', 'MNDY',
    'MNKD', 'MNMD', 'MNOV', 'MNPR', 'MNRO', 'MNSB', 'MNSBP', 'MNST', 'MNTK',
    'MNTL', 'MNTS', 'MNY', 'MOB', 'MOBX', 'MODD', 'MODL', 'MODV', 'MOFG',
    'MOGO', 'MOLN', 'MOMO', 'MOOD', 'MORN', 'MOVE', 'MPAA', 'MPB', 'MPWR',
    'MQ', 'MQQQ', 'MRAL', 'MRAM', 'MRBK', 'MRCC', 'MRCY', 'MREO', 'MRKR',
    'MRM', 'MRNA', 'MRNO', 'MRSN', 'MRTN', 'MRUS', 'MRVI', 'MRVL', 'MRX',
    'MSAI', 'MSBI', 'MSBIP', 'MSDD', 'MSEX', 'MSFD', 'MSFL', 'MSFT', 'MSFU',
    'MSGM', 'MSGY', 'MSPR', 'MSS', 'MST', 'MSTP', 'MSTR', 'MSTX', 'MSW',
    'MTC', 'MTCH', 'MTEK', 'MTEN', 'MTEX', 'MTLS', 'MTRX', 'MTSI', 'MTSR',
    'MTVA', 'MU', 'MUD', 'MULL', 'MULN', 'MURA', 'MUU', 'MVBF', 'MVIS',
    'MVLL', 'MVST', 'MWYN', 'MXCT', 'MXL', 'MYCF', 'MYCG', 'MYCH', 'MYCI',
    'MYCJ', 'MYCK', 'MYCL', 'MYCM', 'MYCN', 'MYFW', 'MYGN', 'MYMF', 'MYMG',
    'MYMH', 'MYMI', 'MYMJ', 'MYNZ', 'MYPS', 'MYRG', 'MYSE', 'MYSZ', 'MZTI',
    'NA', 'NAAS', 'NAGE', 'NAII', 'NAKA', 'NAMI', 'NAMM', 'NAMS', 'NAMSW',
    'NAOV', 'NATH', 'NATO', 'NATR', 'NAUT', 'NAVI', 'NB', 'NBBK', 'NBIS',
    'NBIX', 'NBN', 'NBTB', 'NBTX', 'NCEW', 'NCI', 'NCIQ', 'NCMI', 'NCNA',
    'NCNO', 'NCPB', 'NCPL', 'NCRA', 'NCSM', 'NCT', 'NCTY', 'NDAA', 'NDAQ',
    'NDLS', 'NDRA', 'NDSN', 'NECB', 'NEGG', 'NEHC', 'NEO', 'NEOG', 'NEON',
    'NEOV', 'NEPH', 'NERD', 'NERV', 'NESR', 'NETD', 'NETDU', 'NEUP', 'NEWT',
    'NEWTG', 'NEWTH', 'NEWTI', 'NEWTZ', 'NEWZ', 'NEXM', 'NEXN', 'NEXT',
    'NFBK', 'NFE', 'NFLX', 'NFTY', 'NFXL', 'NFXS', 'NGNE', 'NHIC', 'NHICU',
    'NHPAP', 'NHPBP', 'NHTC', 'NICE', 'NIKL', 'NIPG', 'NISN', 'NITO', 'NIU',
    'NIVF', 'NIXT', 'NIXX', 'NKSH', 'NKTR', 'NKTX', 'NLSP', 'NMFC', 'NMFCZ',
    'NMIH', 'NMPAU', 'NMRA', 'NMRK', 'NMTC', 'NN', 'NNAVW', 'NNBR', 'NNDM',
    'NNE', 'NNNN', 'NNOX', 'NODK', 'NOEM', 'NOEMU', 'NOTV', 'NOVT', 'NOWL',
    'NPAC', 'NPACU', 'NPCE', 'NPFI', 'NRC', 'NRDS', 'NRES', 'NRIM', 'NRIX',
    'NRSN', 'NRXP', 'NSCR', 'NSI', 'NSIT', 'NSPR', 'NSSC', 'NSTS', 'NSYS',
    'NTAP', 'NTCL', 'NTCT', 'NTES', 'NTGR', 'NTHI', 'NTIC', 'NTLA', 'NTNX',
    'NTRA', 'NTRB', 'NTRP', 'NTRS', 'NTRSO', 'NTWK', 'NTWO', 'NTWOU', 'NUAI',
    'NUKK', 'NUSB', 'NUTR', 'NUTX', 'NUVL', 'NUWE', 'NVA', 'NVAX', 'NVCR',
    'NVCT', 'NVD', 'NVDA', 'NVDD', 'NVDG', 'NVDL', 'NVDS', 'NVDU', 'NVEC',
    'NVEE', 'NVFY', 'NVMI', 'NVNI', 'NVNO', 'NVTS', 'NVVE', 'NVVEW', 'NVX',
    'NVYY', 'NWBI', 'NWE', 'NWFL', 'NWGL', 'NWL', 'NWPX', 'NWS', 'NWSA',
    'NWTG', 'NWTN', 'NWTNW', 'NXGL', 'NXGLW', 'NXL', 'NXLIW', 'NXPI', 'NXPL',
    'NXST', 'NXT', 'NXTC', 'NXTG', 'NXTT', 'NXXT', 'NYAX', 'NYMT', 'NYMTG',
    'NYMTH', 'NYMTI', 'NYMTL', 'NYMTM', 'NYMTN', 'NYMTZ', 'NYXH', 'NZAC',
    'NZUS', 'OABI', 'OABIW', 'OACC', 'OACCU', 'OAKU', 'OAKUU', 'OBA',
    'OBAWU', 'OBIL', 'OBIO', 'OBLG', 'OBT', 'OCC', 'OCCI', 'OCCIM', 'OCCIN',
    'OCCIO', 'OCFC', 'OCG', 'OCGN', 'OCS', 'OCSAW', 'OCSL', 'OCTO', 'OCUL',
    'ODD', 'ODDS', 'ODFL', 'ODP', 'ODYS', 'OESX', 'OFAL', 'OFIX', 'OFLX',
    'OFS', 'OFSSH', 'OFSSO', 'OGI', 'OKLL', 'OKTA', 'OKUR', 'OKYO', 'OLB',
    'OLED', 'OLLI', 'OLMA', 'OLPX', 'OM', 'OMAB', 'OMCC', 'OMCL', 'OMDA',
    'OMER', 'OMEX', 'OMH', 'OMSE', 'ON', 'ONB', 'ONBPO', 'ONBPP', 'ONC',
    'ONCHU', 'ONCO', 'ONCY', 'ONDS', 'ONEG', 'ONEQ', 'ONEW', 'ONFO', 'ONFOW',
    'ONMD', 'OOQB', 'OOSB', 'OP', 'OPAL', 'OPBK', 'OPCH', 'OPEN', 'OPI',
    'OPINL', 'OPK', 'OPOF', 'OPPJ', 'OPRA', 'OPRT', 'OPRX', 'OPT', 'OPTX',
    'OPTZ', 'OPXS', 'ORCX', 'ORGN', 'ORGO', 'ORIC', 'ORIQU', 'ORIS', 'ORKA',
    'ORKT', 'ORLY', 'ORMP', 'ORR', 'ORRF', 'OS', 'OSBC', 'OSIS', 'OSPN',
    'OSRH', 'OSS', 'OST', 'OSUR', 'OSW', 'OTEX', 'OTGL', 'OTLK', 'OTLY',
    'OTRK', 'OTTR', 'OUST', 'OVBC', 'OVID', 'OVLY', 'OXBR', 'OXLC', 'OXLCG',
    'OXLCI', 'OXLCL', 'OXLCN', 'OXLCO', 'OXLCP', 'OXLCZ', 'OXSQ', 'OXSQG',
    'OXSQH', 'OXSQZ', 'OYSE', 'OYSEU', 'OZEM', 'OZK', 'OZKAP', 'PAA', 'PABD',
    'PABU', 'PACB', 'PACH', 'PACHU', 'PAGP', 'PAHC', 'PAL', 'PALD', 'PALI',
    'PALU', 'PAMT', 'PANG', 'PANL', 'PANW', 'PARA', 'PARAA', 'PASG', 'PATK',
    'PATN', 'PAVM', 'PAVS', 'PAX', 'PAYO', 'PAYS', 'PAYX', 'PBBK', 'PBFS',
    'PBHC', 'PBM', 'PBPB', 'PBQQ', 'PBYI', 'PC', 'PCAP', 'PCAPU', 'PCAR',
    'PCB', 'PCH', 'PCLA', 'PCMM', 'PCRX', 'PCSA', 'PCSC', 'PCT', 'PCTTU',
    'PCTTW', 'PCTY', 'PCVX', 'PCYO', 'PDBA', 'PDBC', 'PDD', 'PDDL', 'PDEX',
    'PDFS', 'PDLB', 'PDP', 'PDSB', 'PDYN', 'PDYNW', 'PEBK', 'PEBO', 'PECO',
    'PEGA', 'PELI', 'PELIU', 'PENG', 'PENN', 'PEP', 'PEPG', 'PEPS', 'PERI',
    'PESI', 'PET', 'PETS', 'PETWW', 'PETZ', 'PEY', 'PEZ', 'PFAI', 'PFBC',
    'PFF', 'PFG', 'PFI', 'PFIS', 'PFM', 'PFSA', 'PFX', 'PFXNZ', 'PGAC',
    'PGACU', 'PGC', 'PGEN', 'PGJ', 'PGNY', 'PGY', 'PGYWW', 'PHAR', 'PHAT',
    'PHH', 'PHIO', 'PHLT', 'PHO', 'PHOE', 'PHUN', 'PHVS', 'PI', 'PID', 'PIE',
    'PIII', 'PIIIW', 'PINC', 'PIO', 'PIZ', 'PKBK', 'PKOH', 'PKW', 'PLAB',
    'PLAY', 'PLBC', 'PLBL', 'PLBY', 'PLCE', 'PLL', 'PLMK', 'PLMKU', 'PLMR',
    'PLPC', 'PLRX', 'PLRZ', 'PLSE', 'PLT', 'PLTD', 'PLTG', 'PLTK', 'PLTR',
    'PLTU', 'PLTZ', 'PLUG', 'PLUR', 'PLUS', 'PLUT', 'PLXS', 'PMAX', 'PMBS',
    'PMCB', 'PMEC', 'PMN', 'PMTR', 'PMTRU', 'PMTS', 'PMVP', 'PN', 'PNBK',
    'PNFP', 'PNFPP', 'PNQI', 'PNRG', 'PNTG', 'POAI', 'POCI', 'PODC', 'PODD',
    'POET', 'POLA', 'POLE', 'POLEU', 'PONY', 'POOL', 'POWI', 'POWL', 'POWW',
    'POWWP', 'PPBI', 'PPBT', 'PPC', 'PPCB', 'PPH', 'PPI', 'PPIH', 'PPSI',
    'PPTA', 'PQAP', 'PQJA', 'PQJL', 'PQOC', 'PRAA', 'PRAX', 'PRCH', 'PRCT',
    'PRDO', 'PRE', 'PRENW', 'PRFX', 'PRFZ', 'PRGS', 'PRLD', 'PRME', 'PRN',
    'PROF', 'PROK', 'PROP', 'PROV', 'PRPH', 'PRPL', 'PRPO', 'PRQR', 'PRSO',
    'PRTA', 'PRTC', 'PRTG', 'PRTH', 'PRTS', 'PRVA', 'PRZO', 'PSC', 'PSCC',
    'PSCD', 'PSCE', 'PSCF', 'PSCH', 'PSCI', 'PSCM', 'PSCT', 'PSCU', 'PSEC',
    'PSET', 'PSHG', 'PSIG', 'PSIX', 'PSKY', 'PSL', 'PSMT', 'PSNL', 'PSNY',
    'PSNYW', 'PSTR', 'PSTV', 'PSWD', 'PT', 'PTC', 'PTCT', 'PTEC', 'PTEN',
    'PTF', 'PTGX', 'PTH', 'PTHL', 'PTIR', 'PTIX', 'PTLE', 'PTLO', 'PTMN',
    'PTNM', 'PTNQ', 'PTON', 'PUBM', 'PUI', 'PULM', 'PVBC', 'PVLA', 'PWM',
    'PWOD', 'PWP', 'PWRD', 'PXI', 'PXLW', 'PXS', 'PXSAW', 'PY', 'PYPD',
    'PYPG', 'PYPL', 'PYXS', 'PYZ', 'PZZA', 'QABA', 'QAT', 'QB', 'QBIG',
    'QBUF', 'QCLN', 'QCLR', 'QCMD', 'QCML', 'QCMU', 'QCOM', 'QCRH', 'QDEL',
    'QDTY', 'QETA', 'QETAU', 'QFIN', 'QGRD', 'QH', 'QHDG', 'QIPT', 'QLGN',
    'QLYS', 'QMCO', 'QMID', 'QMMM', 'QMOM', 'QNCX', 'QNRX', 'QNST', 'QNTM',
    'QNXT', 'QOWZ', 'QPUX', 'QQA', 'QQDN', 'QQEW', 'QQHG', 'QQJG', 'QQLV',
    'QQMG', 'QQQ', 'QQQA', 'QQQE', 'QQQG', 'QQQH', 'QQQI', 'QQQJ', 'QQQM',
    'QQQP', 'QQQS', 'QQQT', 'QQQX', 'QQQY', 'QQUP', 'QQWZ', 'QQXL', 'QQXT',
    'QRHC', 'QRMI', 'QRVO', 'QSEA', 'QSEAU', 'QSG', 'QSI', 'QSIX', 'QSML',
    'QTEC', 'QTOP', 'QTR', 'QTRX', 'QTTB', 'QTUM', 'QUBT', 'QUIK', 'QUMSU',
    'QURE', 'QVAL', 'QVCGA', 'QVCGP', 'QXQ', 'QYLD', 'QYLG', 'RAA', 'RAAQ',
    'RAAQU', 'RADX', 'RAIL', 'RAIN', 'RAND', 'RANG', 'RANGU', 'RANI', 'RAPP',
    'RAPT', 'RARE', 'RAVE', 'RAY', 'RAYA', 'RAYS', 'RBB', 'RBBN', 'RBCAA',
    'RBIL', 'RBKB', 'RBNE', 'RCAT', 'RCEL', 'RCGE', 'RCKT', 'RCKY', 'RCMT',
    'RCON', 'RCT', 'RDAC', 'RDACU', 'RDAG', 'RDAGU', 'RDCM', 'RDGT', 'RDHL',
    'RDI', 'RDIB', 'RDNT', 'RDNW', 'RDTL', 'RDTY', 'RDVT', 'RDVY', 'RDWR',
    'RDZN', 'REAI', 'REAL', 'REAX', 'REBN', 'RECT', 'REE', 'REFI', 'REFR',
    'REG', 'REGCO', 'REGCP', 'REGN', 'REIT', 'REKR', 'RELI', 'RELL', 'RELY',
    'REMG', 'RENB', 'RENT', 'REPL', 'RETO', 'REVB', 'REVBW', 'REYN', 'RFAI',
    'RFAIU', 'RFDI', 'RFEM', 'RFEU', 'RFIL', 'RGC', 'RGCO', 'RGEN', 'RGLD',
    'RGLO', 'RGNX', 'RGP', 'RGS', 'RGTI', 'RGTIW', 'RGTX', 'RHLD', 'RIBB',
    'RIBBU', 'RICK', 'RIFR', 'RIGL', 'RILY', 'RILYG', 'RILYK', 'RILYL',
    'RILYN', 'RILYP', 'RILYT', 'RILYZ', 'RIME', 'RING', 'RINT', 'RIOT',
    'RITR', 'RIVN', 'RKDA', 'RKLB', 'RKLX', 'RLAY', 'RLMD', 'RLYB', 'RMBI',
    'RMBL', 'RMBS', 'RMCF', 'RMCO', 'RMNI', 'RMR', 'RMSG', 'RMTI', 'RNA',
    'RNAC', 'RNAZ', 'RNBW', 'RNEM', 'RNIN', 'RNRG', 'RNTX', 'RNW', 'RNXT',
    'ROAD', 'ROBT', 'ROCK', 'ROE', 'ROIV', 'ROKU', 'ROMA', 'ROOT', 'ROP',
    'ROST', 'RPAY', 'RPD', 'RPID', 'RPRX', 'RPTX', 'RR', 'RRBI', 'RRGB',
    'RRR', 'RSLS', 'RSSS', 'RSVR', 'RTAC', 'RTACU', 'RTH', 'RTXG', 'RUBI',
    'RUM', 'RUMBW', 'RUN', 'RUNN', 'RUSC', 'RUSHA', 'RUSHB', 'RVMD', 'RVNL',
    'RVPH', 'RVPHW', 'RVSB', 'RVSN', 'RVYL', 'RWAY', 'RWAYL', 'RWAYZ',
    'RXRX', 'RXST', 'RXT', 'RYAAY', 'RYET', 'RYOJ', 'RYTM', 'RZLT', 'RZLV',
    'SABR', 'SABS', 'SABSW', 'SAFT', 'SAFX', 'SAGE', 'SAGT', 'SAIA', 'SAIC',
    'SAIH', 'SAIL', 'SAMG', 'SANA', 'SANG', 'SANM', 'SANW', 'SARK', 'SATL',
    'SATS', 'SAVA', 'SBAC', 'SBC', 'SBCF', 'SBET', 'SBFG', 'SBFM', 'SBGI',
    'SBLK', 'SBRA', 'SBUX', 'SCAG', 'SCDS', 'SCHL', 'SCKT', 'SCLX', 'SCLXW',
    'SCNI', 'SCNX', 'SCOR', 'SCPH', 'SCSC', 'SCVL', 'SCWO', 'SCYX', 'SCZ',
    'SDA', 'SDAWW', 'SDG', 'SDGR', 'SDHI', 'SDHIU', 'SDM', 'SDOT', 'SDSI',
    'SDST', 'SDTY', 'SDVY', 'SEAT', 'SEATW', 'SEDG', 'SEED', 'SEEM', 'SEER',
    'SEGG', 'SEIC', 'SEIE', 'SEIS', 'SELF', 'SELX', 'SENEA', 'SENEB', 'SEPN',
    'SERA', 'SERV', 'SETM', 'SEVN', 'SEZL', 'SFBC', 'SFD', 'SFHG', 'SFIX',
    'SFLO', 'SFM', 'SFNC', 'SFST', 'SFWL', 'SGA', 'SGBX', 'SGC', 'SGD',
    'SGHT', 'SGLY', 'SGMA', 'SGML', 'SGMO', 'SGMT', 'SGRP', 'SGRY', 'SHBI',
    'SHC', 'SHEN', 'SHFS', 'SHFSW', 'SHIM', 'SHIP', 'SHLS', 'SHMD', 'SHOO',
    'SHOP', 'SHOT', 'SHPD', 'SHPH', 'SHPU', 'SHRY', 'SHV', 'SHY', 'SIBN',
    'SIDU', 'SIEB', 'SIFY', 'SIGA', 'SIGI', 'SIGIP', 'SILC', 'SILO', 'SIMA',
    'SIMAU', 'SIMO', 'SINT', 'SION', 'SIRI', 'SISI', 'SITM', 'SIXG', 'SJ',
    'SJCP', 'SJLD', 'SKBL', 'SKIN', 'SKK', 'SKOR', 'SKRE', 'SKWD', 'SKYE',
    'SKYQ', 'SKYT', 'SKYU', 'SKYW', 'SKYX', 'SKYY', 'SLAB', 'SLDB', 'SLDE',
    'SLDP', 'SLDPW', 'SLE', 'SLGL', 'SLM', 'SLMBP', 'SLN', 'SLNG', 'SLNH',
    'SLNHP', 'SLNO', 'SLP', 'SLQD', 'SLRC', 'SLRX', 'SLS', 'SLSN', 'SLVO',
    'SLVR', 'SLXN', 'SMBC', 'SMCC', 'SMCF', 'SMCI', 'SMCL', 'SMCO', 'SMCX',
    'SMCZ', 'SMH', 'SMHX', 'SMID', 'SMLR', 'SMMT', 'SMPL', 'SMRI', 'SMSI',
    'SMST', 'SMTC', 'SMTI', 'SMTK', 'SMX', 'SMXT', 'SNAL', 'SNBR', 'SNCR',
    'SNCY', 'SND', 'SNDK', 'SNDL', 'SNDX', 'SNES', 'SNEX', 'SNFCA', 'SNGX',
    'SNOA', 'SNPS', 'SNRE', 'SNSE', 'SNSR', 'SNT', 'SNTG', 'SNTI', 'SNWV',
    'SNY', 'SNYR', 'SOBR', 'SOCAU', 'SOCL', 'SOFI', 'SOFX', 'SOGP', 'SOHO',
    'SOHOB', 'SOHON', 'SOHOO', 'SOHU', 'SOLT', 'SOLZ', 'SOND', 'SONDW',
    'SONM', 'SONN', 'SONO', 'SOPA', 'SOPH', 'SORA', 'SOTK', 'SOUN', 'SOUNW',
    'SOUX', 'SOWG', 'SOXQ', 'SOXX', 'SPAI', 'SPAM', 'SPAQ', 'SPBC', 'SPC',
    'SPCB', 'SPCX', 'SPCY', 'SPEGU', 'SPFI', 'SPHL', 'SPKL', 'SPKLU', 'SPNS',
    'SPOK', 'SPPL', 'SPRC', 'SPRO', 'SPRX', 'SPRY', 'SPSC', 'SPT', 'SPTN',
    'SPWH', 'SPWR', 'SPXD', 'SPYQ', 'SQFT', 'SQFTP', 'SQLV', 'SQQQ', 'SRAD',
    'SRBK', 'SRCE', 'SRDX', 'SRET', 'SRPT', 'SRRK', 'SRTS', 'SRZN', 'SSBI',
    'SSEAU', 'SSII', 'SSKN', 'SSNC', 'SSP', 'SSRM', 'SSSS', 'SSSSL', 'SSTI',
    'SSYS', 'STAA', 'STAI', 'STAK', 'STBA', 'STEC', 'STEP', 'STFS', 'STGW',
    'STHO', 'STI', 'STIM', 'STKH', 'STKL', 'STKS', 'STLD', 'STNC', 'STNE',
    'STOK', 'STRA', 'STRC', 'STRD', 'STRF', 'STRK', 'STRL', 'STRM', 'STRO',
    'STRR', 'STRRP', 'STRS', 'STRT', 'STRZ', 'STSS', 'STSSW', 'STTK', 'STX',
    'SUGP', 'SUNE', 'SUNS', 'SUPN', 'SUPP', 'SUPX', 'SURG', 'SUSB', 'SUSC',
    'SUSL', 'SUUN', 'SVA', 'SVC', 'SVCC', 'SVCCU', 'SVCO', 'SVII', 'SVIIU',
    'SVRA', 'SVRE', 'SWAG', 'SWBI', 'SWIM', 'SWIN', 'SWKH', 'SWKHL', 'SWKS',
    'SWP', 'SWVL', 'SWVLW', 'SXTC', 'SXTP', 'SY', 'SYBT', 'SYBX', 'SYM',
    'SYNA', 'SYPR', 'SYRE', 'SYTA', 'SYTAW', 'SZZL', 'SZZLU', 'TACH',
    'TACHU', 'TACO', 'TACOU', 'TACT', 'TAIT', 'TALK', 'TANH', 'TAOP', 'TAOX',
    'TARA', 'TARK', 'TARS', 'TASK', 'TATT', 'TAVI', 'TAVIU', 'TAX', 'TAXE',
    'TAXI', 'TAXS', 'TAXT', 'TAYD', 'TBBK', 'TBCH', 'TBH', 'TBHC', 'TBIL',
    'TBLA', 'TBLD', 'TBMC', 'TBPH', 'TBRG', 'TC', 'TCBI', 'TCBIO', 'TCBK',
    'TCBS', 'TCBX', 'TCHI', 'TCMD', 'TCOM', 'TCPC', 'TCRT', 'TCRX', 'TCX',
    'TDAC', 'TDACU', 'TDI', 'TDIC', 'TDIV', 'TDSB', 'TDSC', 'TDTH', 'TDUP',
    'TEAD', 'TEAM', 'TECH', 'TECTP', 'TECX', 'TEKY', 'TELA', 'TELO', 'TEM',
    'TENB', 'TENX', 'TER', 'TERN', 'TEXN', 'TFNS', 'TFSL', 'TGL', 'TGTX',
    'TH', 'THAR', 'THCH', 'THFF', 'THMZ', 'THRD', 'THRM', 'THRY', 'THTX',
    'TIGO', 'TIGR', 'TIL', 'TILE', 'TIPT', 'TIRX', 'TITN', 'TIVC', 'TKLF',
    'TKNO', 'TLF', 'TLIH', 'TLN', 'TLPH', 'TLRY', 'TLS', 'TLSA', 'TLSI',
    'TLT', 'TLX', 'TMB', 'TMC', 'TMCI', 'TMCWW', 'TMDX', 'TMED', 'TMET',
    'TMUS', 'TMUSI', 'TMUSL', 'TMUSZ', 'TNDM', 'TNFA', 'TNGX', 'TNMG',
    'TNON', 'TNXP', 'TNYA', 'TOI', 'TOIIW', 'TOMZ', 'TOP', 'TORO', 'TOUR',
    'TOWN', 'TOYO', 'TPCS', 'TPG', 'TPGXL', 'TPIC', 'TPLS', 'TPST', 'TQQQ',
    'TQQY', 'TRAW', 'TRDA', 'TREE', 'TRI', 'TRIB', 'TRIN', 'TRINI', 'TRINZ',
    'TRIP', 'TRMB', 'TRMD', 'TRMK', 'TRML', 'TRNR', 'TRNS', 'TRON', 'TROO',
    'TROW', 'TRS', 'TRSG', 'TRST', 'TRUD', 'TRUE', 'TRUG', 'TRUP', 'TRUT',
    'TRVG', 'TRVI', 'TSAT', 'TSBK', 'TSBX', 'TSCO', 'TSDD', 'TSEL', 'TSEM',
    'TSHA', 'TSL', 'TSLA', 'TSLG', 'TSLL', 'TSLQ', 'TSLR', 'TSLS', 'TSMG',
    'TSMU', 'TSMX', 'TSMZ', 'TSPY', 'TSSI', 'TSYY', 'TTAN', 'TTD', 'TTEC',
    'TTEK', 'TTEQ', 'TTGT', 'TTMI', 'TTNP', 'TTSH', 'TTWO', 'TUG', 'TUGN',
    'TUR', 'TURB', 'TURF', 'TURN', 'TUSK', 'TVA', 'TVACU', 'TVAI', 'TVAIU',
    'TVGN', 'TVRD', 'TVTX', 'TW', 'TWFG', 'TWG', 'TWIN', 'TWNP', 'TWST',
    'TXG', 'TXMD', 'TXN', 'TXRH', 'TXSS', 'TXUE', 'TXUG', 'TYGO', 'TYRA',
    'TZOO', 'TZUP', 'UAE', 'UAL', 'UBCP', 'UBFO', 'UBND', 'UBRL', 'UBSI',
    'UBXG', 'UCAR', 'UCL', 'UCRD', 'UCTT', 'UCYB', 'UDMY', 'UEIC', 'UEVM',
    'UFCS', 'UFG', 'UFIV', 'UFO', 'UFPI', 'UFPT', 'UG', 'UGRO', 'UHG',
    'UHGWW', 'UITB', 'UIVM', 'UK', 'UKOMW', 'ULBI', 'ULCC', 'ULH', 'ULTA',
    'ULVM', 'ULY', 'UMBF', 'UMBFO', 'UMMA', 'UNB', 'UNCY', 'UNHG', 'UNIT',
    'UNIY', 'UNTY', 'UOKA', 'UONE', 'UONEK', 'UPB', 'UPBD', 'UPC', 'UPGR',
    'UPLD', 'UPST', 'UPWK', 'UPXI', 'URBN', 'URGN', 'URNJ', 'UROY', 'USAF',
    'USAR', 'USAU', 'USCB', 'USCL', 'USDX', 'USEA', 'USEG', 'USFI', 'USGO',
    'USGOW', 'USIG', 'USIN', 'USIO', 'USLM', 'USMC', 'USOI', 'USOY', 'USRD',
    'USSH', 'USTB', 'USVM', 'USVN', 'USXF', 'UTEN', 'UTHR', 'UTHY', 'UTMD',
    'UTRE', 'UTSI', 'UTWO', 'UTWY', 'UVSP', 'UXIN', 'UYLD', 'UYSC', 'UYSCU',
    'VABK', 'VACH', 'VACHU', 'VALN', 'VALU', 'VANI', 'VAPE', 'VBIL', 'VBIX',
    'VBNK', 'VBTX', 'VC', 'VCEL', 'VCIC', 'VCICU', 'VCIG', 'VCIT', 'VCLT',
    'VCRB', 'VCSH', 'VCTR', 'VCYT', 'VECO', 'VEEA', 'VEEE', 'VELO', 'VEON',
    'VERA', 'VERB', 'VERI', 'VERO', 'VERU', 'VERV', 'VERX', 'VFF', 'VFLO',
    'VFS', 'VGAS', 'VGASW', 'VGIT', 'VGLT', 'VGSH', 'VGSR', 'VGUS', 'VIASP',
    'VIAV', 'VICR', 'VIGI', 'VIGL', 'VINP', 'VIOT', 'VIR', 'VIRC', 'VITL',
    'VIVK', 'VIVS', 'VIXI', 'VKTX', 'VLCN', 'VLGEA', 'VLY', 'VLYPN', 'VLYPO',
    'VLYPP', 'VMAR', 'VMBS', 'VMD', 'VMEO', 'VNDA', 'VNET', 'VNME', 'VNMEU',
    'VNOM', 'VNQI', 'VOD', 'VOLT', 'VONE', 'VONG', 'VONV', 'VOR', 'VOTE',
    'VOXR', 'VPLS', 'VRA', 'VRAR', 'VRAX', 'VRCA', 'VRDN', 'VREX', 'VRIG',
    'VRM', 'VRME', 'VRNA', 'VRNS', 'VRNT', 'VRRM', 'VRSK', 'VRSN', 'VRTL',
    'VRTX', 'VS', 'VSA', 'VSAT', 'VSDA', 'VSEC', 'VSEE', 'VSME', 'VSMV',
    'VSSYW', 'VSTA', 'VSTL', 'VSTM', 'VTC', 'VTGN', 'VTHR', 'VTIP', 'VTRS',
    'VTSI', 'VTVT', 'VTWG', 'VTWO', 'VTWV', 'VTYX', 'VUZI', 'VVOS', 'VVPR',
    'VWAV', 'VWOB', 'VXUS', 'VYGR', 'VYMI', 'VYNE', 'WABC', 'WABF', 'WAFD',
    'WAFDP', 'WAFU', 'WAI', 'WALD', 'WALDW', 'WASH', 'WATT', 'WAVE', 'WAY',
    'WB', 'WBA', 'WBD', 'WBND', 'WBTN', 'WBUY', 'WCBR', 'WCLD', 'WCT',
    'WDAY', 'WDC', 'WDFC', 'WEEI', 'WEN', 'WENN', 'WENNU', 'WERN', 'WEST',
    'WETH', 'WETO', 'WEYS', 'WFCF', 'WFF', 'WFRD', 'WGMI', 'WGRX', 'WGS',
    'WHF', 'WHFCL', 'WHLR', 'WHLRD', 'WHLRL', 'WHLRP', 'WHWK', 'WILC',
    'WIMI', 'WINA', 'WINC', 'WING', 'WINT', 'WISE', 'WIX', 'WKEY', 'WKHS',
    'WKSP', 'WLAC', 'WLACU', 'WLDN', 'WLDS', 'WLFC', 'WLGS', 'WMG', 'WNDY',
    'WNEB', 'WNW', 'WOK', 'WOOD', 'WOOF', 'WORX', 'WPRT', 'WRAP', 'WRD',
    'WRLD', 'WRND', 'WSBC', 'WSBCP', 'WSBF', 'WSBK', 'WSC', 'WSFS', 'WSML',
    'WTBA', 'WTBN', 'WTF', 'WTFC', 'WTFCN', 'WTG', 'WTGUU', 'WTIP', 'WTMU',
    'WTMY', 'WTO', 'WTW', 'WULF', 'WVE', 'WVVI', 'WVVIP', 'WW', 'WWD', 'WXM',
    'WYFI', 'WYHG', 'WYNN', 'XAGE', 'XAIR', 'XAIX', 'XBIL', 'XBIO', 'XBIT',
    'XBP', 'XBTY', 'XCH', 'XCNY', 'XCUR', 'XEL', 'XELB', 'XENE', 'XERS',
    'XFIX', 'XFOR', 'XGN', 'XHG', 'XHLD', 'XLO', 'XMAG', 'XMTR', 'XNCR',
    'XNET', 'XOMA', 'XOMAO', 'XOMAP', 'XOMX', 'XOMZ', 'XOS', 'XOVR', 'XP',
    'XPEL', 'XPON', 'XRAY', 'XRPI', 'XRPT', 'XRTX', 'XRX', 'XT', 'XTIA',
    'XTKG', 'XTLB', 'XWEL', 'XXII', 'XYLO', 'XYZG', 'YAAS', 'YB', 'YGMZ',
    'YHC', 'YHGJ', 'YHNA', 'YHNAU', 'YI', 'YIBO', 'YJ', 'YLDE', 'YMAB',
    'YMAT', 'YMT', 'YNOT', 'YOKE', 'YORK', 'YORKU', 'YORW', 'YOSH', 'YOUL',
    'YQQQ', 'YSPY', 'YSXT', 'YTRA', 'YXT', 'YYAI', 'YYGH', 'Z', 'ZAP',
    'ZBAI', 'ZBAO', 'ZBIO', 'ZBRA', 'ZCMD', 'ZD', 'ZDAI', 'ZENA', 'ZENV',
    'ZEO', 'ZEUS', 'ZG', 'ZIMV', 'ZION', 'ZIONP', 'ZIPP', 'ZJK', 'ZJYL',
    'ZKIN', 'ZLAB', 'ZM', 'ZNB', 'ZNTL', 'ZOOZ', 'ZS', 'ZSPC', 'ZTEK',
    'ZTEN', 'ZTOP', 'ZTRE', 'ZTWO', 'ZUMZ', 'ZURA', 'ZVRA', 'ZYBT', 'ZYME',
    'ZYXI', 'ZZZ'
]

    import random
    random.seed(42)
    codes = random.sample(codes, 200)

    #for code in codes:
    #    data_loader.load_d_data(f'{code}')

    total_list = []
    rea_code  = []
    for code in codes:
        temp = find_boss.preprocessing(code, pd.read_csv(f"data/raw/d_csv/{code}_data.csv"))
        if temp != None:
            total_list.append(temp)
            rea_code.append(code)

    total_df = pd.DataFrame(total_list)

    find_boss.scale_optics(rea_code, total_df)

    # test.current_price('AAPL')
    # test.fundamental('AAPL')


    # model_a = balance(name='model_a', initial_cash=1000)
    
    # model_a.buy('AAPL',3,230)
    
    # print(model_a.total_value())
    # print(model_a.unreal_pnl())
    # model_a.sell('AAPL',3,200)



    
